version: "3.8"
services:
  elasticsearch:
    image: elasticsearch:8.16.1  
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - elk-network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: kibana:8.16.1
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk-network
    depends_on:
      elasticsearch:
        condition: service_healthy

  logstash:
    image: logstash:8.16.1
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/data:/usr/share/logstash/data
      - service1-log:/usr/share/logstash/service1/logs
      - service2-log:/usr/share/logstash/service2/logs
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - elk-network
    depends_on:
      elasticsearch:
        condition: service_healthy
      
volumes:
  service1-log:
    driver: local
  service2-log:
    driver: local
    
networks:
  elk-network:
    external: true
